### ISSUE TITLE
Does this work with the newest version of chrome?

### ISSUE THREAD

**Issue by chavenor** [airmrcr/injector-chrome#13]
I wrote a js snippet but nothing seems to be happening?   This is what's in the snippet which works in the google console. 

Is it possibly that jquery dosn't work? 

```js
//working-js-example

var hours_worked = $('#custom_fields_list > div > li > span.info-label');
var searchText = "Hours Worked";
var found = null;
var hours_worked_json;

for (var i = 0; i < hours_worked.length; i++) {
  if (hours_worked[i].textContent == searchText) {
    found = hours_worked[i];
    break;
  }
}

if (found){
	hours_worked_json = found.previousElementSibling.innerText;
	console.log(hours_worked_json);
}

var hours_table_contenct = `<div style="display: none; background-color=#FFF;">
<p>Stuff here. </p>
</div>
        <a href='#' onclick='hideinfo(); return false;'><i> <-- Hide --><i/></a>`


function showinfo(){
	found.previousElementSibling.innerHTML= hours_table_contenct;
	var newdiv = found.previousElementSibling.getElementsByTagName('div')[0];
	newdiv.style.zIndex = 100;
	newdiv.style.position = "absolute";
	newdiv.style.top = found.previousElementSibling.offsetTop + 'px';
	newdiv.style.left = String(parseInt(found.previousElementSibling.offsetLeft) + 170) +'px';
	newdiv.style.display = "inline";
	newdiv.style.width = '650px';
} 

function hideinfo(){
	found.previousElementSibling.innerHTML= "<a href='#' onclick='showinfo(); return false;'><i> <-- Click --><i/></a>"
} 

hideinfo();   

```

**Comment by airmrcr** [comment]
@chavenor Sorry for taking so long to get back to you. I just tested Injector on the latest stable version of Chrome and I'm not seeing any issues with my test snippets.

Are you sure that jQuery is available on the page that you're targetting? Are you seeing any errors in the web dev tools?

My best advice would be to add a `debugger` statement somewhere in your snippet to trigger a breakpoint when Injector inserts your script into the page. That should allow you to get to the root of the issue.

**Comment by chavenor** [comment]
No worries, I built an extension from scratch. ;) 

But I wasn't getting any errors or console stuff -- perhaps included a working example could help future users.   Just a thought.   Heck you could send people to a webpage that you own and have ads displayed on to help pay for hosting and dev costs.

Thanks! 

Casey
